name: Deploy to GitHub Pages
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOMO_DOJO: ${{ secrets.DOMO_DOJO }},
      DOMO_DOJO_ACCESS_TOKEN: ${{ secrets.DOMO_DOJO_ACCESS_TOKEN }}
    steps:
      - uses: fastai/workflows/quarto-ghp@master
