name: CI
on: [workflow_dispatch, pull_request, push]
env:
  DOMO_DOJO: ${{ secrets.DOMO_DOJO }},
  DOMO_DOJO_ACCESS_TOKEN: ${{ secrets.DOMO_DOJO_ACCESS_TOKEN }}
jobs:
  echosecrets:
    runs-on: windows-latest
    steps:
      - name: print github secrets
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.DOMO_DOJO_ACCESS_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
