name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOJO_PASSWORD: ${{ secrets.DOJO_PASSWORD }},
      DOMO_DOJO_ACCESS_TOKEN: ${{ secrets.DOMO_DOJO_ACCESS_TOKEN }},
      DOJO_DATASET_ID : ${{ secrets.DOJO_DATASET_ID }}
    steps:
      - uses: fastai/workflows/nbdev-ci@master
